#!/bin/bash
# Permanent Dashboard Fix Deployment Script
# This will make the dashboard work correctly after page refresh

echo "=========================================="
echo "CoreChain Dashboard - Permanent Fix"
echo "=========================================="
echo ""
echo "The dashboard fix has been committed to GitHub."
echo "To make it permanent on AWS, run ONE of these options:"
echo ""
echo "=========================================="
echo "OPTION 1: SSH + Git Pull (RECOMMENDED)"
echo "=========================================="
echo ""
echo "ssh ubuntu@54.173.119.88 << 'ENDSSH'"
echo "  cd /home/ubuntu/corechain || cd /var/www/corechain || cd ~/corechain"
echo "  git pull origin main"
echo "  sudo cp dashboard/index.html /var/www/html/index.html"
echo "  echo '✅ Dashboard updated successfully!'"
echo "ENDSSH"
echo ""
echo "=========================================="
echo "OPTION 2: Direct File Upload"
echo "=========================================="
echo ""
echo "# From your local machine:"
echo "scp dashboard/index.html ubuntu@54.173.119.88:/tmp/dashboard-fixed.html"
echo ""
echo "# Then SSH and move it:"
echo "ssh ubuntu@54.173.119.88"
echo "sudo mv /tmp/dashboard-fixed.html /var/www/html/index.html"
echo ""
echo "=========================================="
echo "WHAT WAS FIXED (Permanent Changes)"
echo "=========================================="
echo ""
echo "1. ✅ API_URL: Changed from port 8000 to relative paths"
echo "   - Now uses nginx proxy on port 80"
echo "   - All /api/* requests work correctly"
echo ""
echo "2. ✅ BLOCKCHAIN_URL: Set to port 7050"
echo "   - Blockchain service accessible"
echo "   - Stats and transactions display"
echo ""
echo "3. ✅ loadHospitals: Fixed array handling"
echo "   - API returns array directly"
echo "   - Added fallback for both formats"
echo "   - Shows hospital status with color"
echo ""
echo "=========================================="
echo "AFTER DEPLOYMENT"
echo "=========================================="
echo ""
echo "1. Clear browser cache: Ctrl+Shift+R (or Cmd+Shift+R on Mac)"
echo "2. Navigate to: http://54.173.119.88"
echo "3. Dashboard should show:"
echo "   ✅ Status: running"
echo "   ✅ FL Round: 2 / 10"
echo "   ✅ Connected Hospitals: 1 / 1 (FL Test Hospital)"
echo "   ✅ Blockchain: 1 Block, 1 Transaction"
echo ""
echo "4. Refresh the page - it should STAY working!"
echo ""
echo "=========================================="
echo "VERIFICATION"
echo "=========================================="
echo ""
echo "After deployment, verify the fix is permanent:"
echo ""
echo "ssh ubuntu@54.173.119.88"
echo "grep 'Use relative paths' /var/www/html/index.html"
echo ""
echo "If you see the comment, the fix is deployed!"
echo ""
