#!/bin/bash
# Quick fix script to update the dashboard on AWS
# This creates a simple one-liner to update the dashboard file

echo "=== CoreChain Dashboard Fix Deployment ==="
echo ""
echo "The dashboard is currently showing metrics via browser injection,"
echo "but this fix needs to be made permanent on the AWS server."
echo ""
echo "=== Option 1: SSH Access (Recommended) ==="
echo "If you have SSH access to the AWS server, run:"
echo ""
echo "ssh ubuntu@54.173.119.88 << 'EOF'"
echo "cd /home/ubuntu/corechain"
echo "git pull origin main"
echo "sudo cp dashboard/index.html /var/www/html/index.html"
echo "echo 'Dashboard updated successfully!'"
echo "EOF"
echo ""
echo "=== Option 2: Direct File Update (If no git on server) ==="
echo "Create a temporary fixed file and upload it:"
echo ""
echo "# On your local machine:"
echo "scp dashboard/index.html ubuntu@54.173.119.88:/tmp/dashboard.html"
echo ""
echo "# Then SSH and move it:"
echo "ssh ubuntu@54.173.119.88"
echo "sudo mv /tmp/dashboard.html /var/www/html/index.html"
echo ""
echo "=== Option 3: Manual Edit on Server ==="
echo "SSH into server and edit the file directly:"
echo ""
echo "ssh ubuntu@54.173.119.88"
echo "sudo nano /var/www/html/index.html"
echo ""
echo "Find line ~739-741 that says:"
echo "  const API_URL = window.location.hostname === 'localhost'"
echo "      ? 'http://localhost:8000'"
echo "      : \`http://\${window.location.hostname}:8000\`;"
echo ""
echo "Replace with:"
echo "  // Use relative paths - nginx on port 80 proxies /api/* to backend"
echo "  const API_URL = '';"
echo ""
echo "Save (Ctrl+O, Enter, Ctrl+X) and refresh browser with Ctrl+Shift+R"
echo ""
echo "=== Current Status ==="
echo "✅ Dashboard showing metrics via browser injection"
echo "✅ API working correctly (status: running, round 2/10)"
echo "⚠️  Fix is temporary - needs permanent deployment"
echo ""
echo "=== What's Fixed ==="
echo "Changed API_URL from hardcoded port 8000 to relative paths"
echo "This allows nginx on port 80 to proxy requests correctly"
echo ""
